spring:
  datasource:
    url: jdbc:h2:mem:librarydb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none    #В проде/разработке используем миграции или schema.sql
    show-sql: false

app:
  questions-resource: questions.csv
  passing-score: 3